"""Add users_setting table

Revision ID: 0b3f8d1a591d
Revises: ca452e732d9f
Create Date: 2026-01-05 09:07:39.676000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3f8d1a591d'
down_revision: Union[str, None] = 'ca452e732d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('app_lang', sa.String(), nullable=False),
    sa.Column('app_explan_lang', sa.String(), nullable=False),
    sa.Column('app_second_subtitle', sa.String(), nullable=False),
    sa.Column('app_target_lang', sa.String(), nullable=False),
    sa.Column('sub_youtube', sa.String(), nullable=False),
    sa.Column('sub_second', sa.String(), nullable=False),
    sa.Column('sub_both', sa.Boolean(), nullable=False),
    sa.Column('sub_font_size', sa.Enum('SMALL', 'REGULAR', 'MEDIUM', 'LARGE', name='fontsize'), nullable=False),
    sa.Column('sub_focus_mode', sa.Boolean(), nullable=False),
    sa.Column('sub_jp_romaji', sa.Boolean(), nullable=False),
    sa.Column('sub_jp_furigana', sa.Boolean(), nullable=False),
    sa.Column('sub_jp_speech_part', sa.Boolean(), nullable=False),
    sa.Column('sub_jp_semantic', sa.Boolean(), nullable=False),
    sa.Column('sub_jp_gaya', sa.Boolean(), nullable=False),
    sa.Column('sub_zh_pinyin', sa.Boolean(), nullable=False),
    sa.Column('sub_zh_character', sa.Enum('SIMPLIFIED', 'TRADITIONAL', name='zhcharacter'), nullable=False),
    sa.Column('echo_listen', sa.Boolean(), nullable=False),
    sa.Column('echo_echo', sa.Boolean(), nullable=False),
    sa.Column('echo_delay', sa.Boolean(), nullable=False),
    sa.Column('echo_speak', sa.Boolean(), nullable=False),
    sa.Column('echo_play', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.Enum('SYSTEM', 'LIGHT', 'DARK', name='theme'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_setting_id'), 'users_setting', ['id'], unique=False)
    op.create_index(op.f('ix_users_setting_user_uuid'), 'users_setting', ['user_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_setting_user_uuid'), table_name='users_setting')
    op.drop_index(op.f('ix_users_setting_id'), table_name='users_setting')
    op.drop_table('users_setting')
    # ### end Alembic commands ###
