"""add_iap_tables

Revision ID: 36fc156e92d7
Revises: 0b3f8d1a591d
Create Date: 2026-07-16 09:45:43.204338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36fc156e92d7'
down_revision: Union[str, None] = '0b3f8d1a591d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iap_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iap_products_id'), 'iap_products', ['id'], unique=False)
    op.create_index(op.f('ix_iap_products_product_id'), 'iap_products', ['product_id'], unique=True)
    op.create_table('iap_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('original_transaction_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_data', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('notification_subtype', sa.String(), nullable=True),
    sa.Column('notification_uuid', sa.String(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iap_transactions_id'), 'iap_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_iap_transactions_original_transaction_id'), 'iap_transactions', ['original_transaction_id'], unique=False)
    op.create_index(op.f('ix_iap_transactions_transaction_id'), 'iap_transactions', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_iap_transactions_user_id'), 'iap_transactions', ['user_id'], unique=False)
    op.create_table('user_entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('original_transaction_id', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew_status', sa.Boolean(), nullable=True),
    sa.Column('will_renew', sa.Boolean(), nullable=True),
    sa.Column('is_in_grace_period', sa.Boolean(), nullable=True),
    sa.Column('grace_period_expires_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_in_billing_retry', sa.Boolean(), nullable=True),
    sa.Column('quantity_remaining', sa.Integer(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_entitlements_id'), 'user_entitlements', ['id'], unique=False)
    op.create_index(op.f('ix_user_entitlements_original_transaction_id'), 'user_entitlements', ['original_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_entitlements_user_id'), 'user_entitlements', ['user_id'], unique=False)
    op.create_index('ix_user_entitlements_user_product', 'user_entitlements', ['user_id', 'product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_entitlements_user_product', table_name='user_entitlements')
    op.drop_index(op.f('ix_user_entitlements_user_id'), table_name='user_entitlements')
    op.drop_index(op.f('ix_user_entitlements_original_transaction_id'), table_name='user_entitlements')
    op.drop_index(op.f('ix_user_entitlements_id'), table_name='user_entitlements')
    op.drop_table('user_entitlements')
    op.drop_index(op.f('ix_iap_transactions_user_id'), table_name='iap_transactions')
    op.drop_index(op.f('ix_iap_transactions_transaction_id'), table_name='iap_transactions')
    op.drop_index(op.f('ix_iap_transactions_original_transaction_id'), table_name='iap_transactions')
    op.drop_index(op.f('ix_iap_transactions_id'), table_name='iap_transactions')
    op.drop_table('iap_transactions')
    op.drop_index(op.f('ix_iap_products_product_id'), table_name='iap_products')
    op.drop_index(op.f('ix_iap_products_id'), table_name='iap_products')
    op.drop_table('iap_products')
    # ### end Alembic commands ###
