"""Add uuid field to users table

Revision ID: ca452e732d9f
Revises: 
Create Date: 2026-01-04 20:20:35.709800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid


# revision identifiers, used by Alembic.
revision: str = 'ca452e732d9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add uuid column as nullable first
    op.add_column('users', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    
    # Step 2: Generate UUIDs for existing rows
    op.execute("UPDATE users SET uuid = gen_random_uuid() WHERE uuid IS NULL")
    
    # Step 3: Make the column NOT NULL and add unique constraint
    op.alter_column('users', 'uuid', nullable=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###
