"""add business_records table

Revision ID: f3104cb366eb
Revises: a1b2c3d4e5f6
Create Date: 2026-09-05 10:39:56.122807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3104cb366eb'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('duration_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_records_change_type'), 'business_records', ['change_type'], unique=False)
    op.create_index(op.f('ix_business_records_id'), 'business_records', ['id'], unique=False)
    op.create_index('ix_business_records_user_created', 'business_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_business_records_user_id'), 'business_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_records_user_id'), table_name='business_records')
    op.drop_index('ix_business_records_user_created', table_name='business_records')
    op.drop_index(op.f('ix_business_records_id'), table_name='business_records')
    op.drop_index(op.f('ix_business_records_change_type'), table_name='business_records')
    op.drop_table('business_records')
    # ### end Alembic commands ###
